name: 'bm.action.bundle_pr'
description: 'Github action for bundle pull request'
inputs:
  NPM_TOKEN:
    description: 'NPM TOKEN needed for npm'
    required: true
    default: 'XXXXXXXXXXXXXXXXX'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.NPM_TOKEN }}

